In [30]:
#importer les packages
import pandas as pd
from dotenv import load_dotenv
from io import BytesIO
import os
import numpy as np
import pandas as pd
import requests
from tqdm.notebook import tqdm
tqdm.pandas()

from utils.correcting_features import corrige_all, corrige_etabli2, corrige_rgp2, corrige_rgp3, corrige_op_ing
from utils.load_corrections import get_all_correctifs_from_google, load_all_correctifs
from utils.traitements import importtab, gentab

In [31]:
# ATTENTION, avant de commencer, s'assurer d'avoir un dossier "INPUT" 
# avec les données au format parquet pour chaque année et un dossier
# POST_GENTAB pour acceuillir les données traitées (attention c'est assez volumineux)

# Modifier la page format du googlesheet si il y a de nouveaux formats cette année
# Modifier également la page D_EPE du googlesheet ESR pour ajouter les EPE de la nouvelle année

In [32]:
DATA_PATH=os.getcwd()

In [33]:
url_atlas='https://docs.google.com/spreadsheet/ccc?key=11NFXSIg6gQMCsMa8zWQQyypvvYBEmfyJfF2yytXqgMk&output=xls'
url_esr='https://docs.google.com/spreadsheet/ccc?key=1FwPq5Qw7Gbgj_sBD6Za4dfDDk6ydozQ99TyRjLkW5d8&output=xls'

VARS_atlas=['COM_U','COM_M', 'ETABLI', 'MINISTER', 'DC', 'NATION', 'ETABLI2', 'FORMAT','CURSUS_LMD', 'DISCIPLI','RGP2', 'RGP3','OP_ING','SECRET']
VARS_esr=['O_DUTBUT','J_LMDDONT','DISCIPLINES_SISE','FORMAT','D_EPE','C_ETABLISSEMENTS']

Charger les données des googlesheets depuis google en local au format .json dans le dossier (pas besoin de le faire à chaque fois, à faire si c'est la première fois OU lors d'une modification sur le.s googlesheet.s)

In [34]:
load_dotenv()  

GRIST_KEY = os.getenv("GRIST_KEY")

#URL et headers pour l'API Grist
grist_url = "https://grist.numerique.gouv.fr/api/docs/aoAbiYjvgr2aw1Pez2s2wj/download/xlsx?header=colId"
headers = {
    "Authorization": f"Bearer {GRIST_KEY}"
}
response = requests.get(grist_url, headers=headers)
response.raise_for_status()  # Vérifie les erreurs HTTP

with BytesIO(response.content) as excel_data:
    communes = pd.read_excel(excel_data, sheet_name=['Commune'], dtype=str, na_filter=False).get("Commune")

In [35]:
#get_all_correctifs_from_google(url_atlas,VARS_atlas,'_atlas')
#get_all_correctifs_from_google(url_esr,VARS_esr,'_esr')

Charger les 2 googlessheets dans le notebook

In [36]:
CORRECTIFS_dict_esr = load_all_correctifs('_esr')
CORRECTIFS_dict = load_all_correctifs('_atlas')

In [37]:
formats=pd.DataFrame(CORRECTIFS_dict_esr['FORMAT']).drop_duplicates()

On charge bien la rentrée scolaire de l'année en cours

In [38]:
rentree_sco=2023

On charge les données correspondantes

In [39]:
df=pd.read_parquet(f"./INPUT/ts{str(rentree_sco)[2:]}d_tot.parquet", engine='fastparquet')

In [40]:
df.columns=[x.upper() for x in df.columns]

In [41]:
df[pd.isna(df.FORMAT)]
#df.loc[(pd.isna(df.FORMAT))&(df.ETABLI=='9830445S'),'FORMAT'] = 'autr'

Empty DataFrame
Columns: [COMPOS, ETABLI, SECTEUR, FORMAT, ENQ, NATION, NATR, SEXE, GROUPE, TYP_DIPL, DISCIPLI, SECTDIS, DIPLOM, REGIME, CURSUS_LMD, UNIV, FLAG_MEEF, HCPGE, DBCOMPTE, BAC_RGRP, ACABAC, ANBAC, PCS, ETABLI_DIFFUSION, AGE, ECHANG, DEGETU, FLAG_REGROUPEMENT, IMPUTATION, INDIC_COMUE, OPPOS, COMUE_RATT, TYPE, ETABLI_RATT, MEFBCP11, MEFST11, HSIFA, DIPLOME_STSAP, FR_ETR_R, FR_ETR_D, FINECOLE, ADRESSE, ADRESSE_UAI, CONTRAT, DENOMINATION_PRINCIPALE_UAI, DEP, DISC, LIBELLE.ROUTAGE, LOCALITE_ACHEMINEMENT_UAI, MINISTERE_TUTELLE, NIVEAU_UAI, NIVFORM, NOMECOLE, PATRONYME_UAI, NATIO, FINANC, LIG, NIVEAU_U, TYPE_LIB, Z_COL1, Z_COL2, Z_COL3, Z_COL4, Z_COL5, Z_COL6, Z_COL7, Z_COL8, Z_COL9, Z_COL10, Z_COL11, Z_COL12, TAB02, TAB04, TAB05, TAB06, TAB07, TAB08, TAB09, TAB10, NEW_ETAB_ANC, NEW_ETAB_RENTREE, FRA, ETR, EFFTOT, EFFTOTN, EFFTOTA, ANNEE, CONTRAT_M, SIGLE_M, SECT_M, NAT_M, COM_M, LIB1_M, LIB2_M, ACA_M, MIN_M, CONTRAT_U, SIGLE_U, SECT_U, NAT_U, ...]
Index: []

[0 rows x 119 columns]

In [42]:
df[pd.isna(df.ETABLI)]

Empty DataFrame
Columns: [COMPOS, ETABLI, SECTEUR, FORMAT, ENQ, NATION, NATR, SEXE, GROUPE, TYP_DIPL, DISCIPLI, SECTDIS, DIPLOM, REGIME, CURSUS_LMD, UNIV, FLAG_MEEF, HCPGE, DBCOMPTE, BAC_RGRP, ACABAC, ANBAC, PCS, ETABLI_DIFFUSION, AGE, ECHANG, DEGETU, FLAG_REGROUPEMENT, IMPUTATION, INDIC_COMUE, OPPOS, COMUE_RATT, TYPE, ETABLI_RATT, MEFBCP11, MEFST11, HSIFA, DIPLOME_STSAP, FR_ETR_R, FR_ETR_D, FINECOLE, ADRESSE, ADRESSE_UAI, CONTRAT, DENOMINATION_PRINCIPALE_UAI, DEP, DISC, LIBELLE.ROUTAGE, LOCALITE_ACHEMINEMENT_UAI, MINISTERE_TUTELLE, NIVEAU_UAI, NIVFORM, NOMECOLE, PATRONYME_UAI, NATIO, FINANC, LIG, NIVEAU_U, TYPE_LIB, Z_COL1, Z_COL2, Z_COL3, Z_COL4, Z_COL5, Z_COL6, Z_COL7, Z_COL8, Z_COL9, Z_COL10, Z_COL11, Z_COL12, TAB02, TAB04, TAB05, TAB06, TAB07, TAB08, TAB09, TAB10, NEW_ETAB_ANC, NEW_ETAB_RENTREE, FRA, ETR, EFFTOT, EFFTOTN, EFFTOTA, ANNEE, CONTRAT_M, SIGLE_M, SECT_M, NAT_M, COM_M, LIB1_M, LIB2_M, ACA_M, MIN_M, CONTRAT_U, SIGLE_U, SECT_U, NAT_U, ...]
Index: []

[0 rows x 119 columns]

In [43]:
df[pd.isna(df.COMPOS)]

Empty DataFrame
Columns: [COMPOS, ETABLI, SECTEUR, FORMAT, ENQ, NATION, NATR, SEXE, GROUPE, TYP_DIPL, DISCIPLI, SECTDIS, DIPLOM, REGIME, CURSUS_LMD, UNIV, FLAG_MEEF, HCPGE, DBCOMPTE, BAC_RGRP, ACABAC, ANBAC, PCS, ETABLI_DIFFUSION, AGE, ECHANG, DEGETU, FLAG_REGROUPEMENT, IMPUTATION, INDIC_COMUE, OPPOS, COMUE_RATT, TYPE, ETABLI_RATT, MEFBCP11, MEFST11, HSIFA, DIPLOME_STSAP, FR_ETR_R, FR_ETR_D, FINECOLE, ADRESSE, ADRESSE_UAI, CONTRAT, DENOMINATION_PRINCIPALE_UAI, DEP, DISC, LIBELLE.ROUTAGE, LOCALITE_ACHEMINEMENT_UAI, MINISTERE_TUTELLE, NIVEAU_UAI, NIVFORM, NOMECOLE, PATRONYME_UAI, NATIO, FINANC, LIG, NIVEAU_U, TYPE_LIB, Z_COL1, Z_COL2, Z_COL3, Z_COL4, Z_COL5, Z_COL6, Z_COL7, Z_COL8, Z_COL9, Z_COL10, Z_COL11, Z_COL12, TAB02, TAB04, TAB05, TAB06, TAB07, TAB08, TAB09, TAB10, NEW_ETAB_ANC, NEW_ETAB_RENTREE, FRA, ETR, EFFTOT, EFFTOTN, EFFTOTA, ANNEE, CONTRAT_M, SIGLE_M, SECT_M, NAT_M, COM_M, LIB1_M, LIB2_M, ACA_M, MIN_M, CONTRAT_U, SIGLE_U, SECT_U, NAT_U, ...]
Index: []

[0 rows x 119 columns]

In [44]:
df[pd.isna(df.SEXE)]

Empty DataFrame
Columns: [COMPOS, ETABLI, SECTEUR, FORMAT, ENQ, NATION, NATR, SEXE, GROUPE, TYP_DIPL, DISCIPLI, SECTDIS, DIPLOM, REGIME, CURSUS_LMD, UNIV, FLAG_MEEF, HCPGE, DBCOMPTE, BAC_RGRP, ACABAC, ANBAC, PCS, ETABLI_DIFFUSION, AGE, ECHANG, DEGETU, FLAG_REGROUPEMENT, IMPUTATION, INDIC_COMUE, OPPOS, COMUE_RATT, TYPE, ETABLI_RATT, MEFBCP11, MEFST11, HSIFA, DIPLOME_STSAP, FR_ETR_R, FR_ETR_D, FINECOLE, ADRESSE, ADRESSE_UAI, CONTRAT, DENOMINATION_PRINCIPALE_UAI, DEP, DISC, LIBELLE.ROUTAGE, LOCALITE_ACHEMINEMENT_UAI, MINISTERE_TUTELLE, NIVEAU_UAI, NIVFORM, NOMECOLE, PATRONYME_UAI, NATIO, FINANC, LIG, NIVEAU_U, TYPE_LIB, Z_COL1, Z_COL2, Z_COL3, Z_COL4, Z_COL5, Z_COL6, Z_COL7, Z_COL8, Z_COL9, Z_COL10, Z_COL11, Z_COL12, TAB02, TAB04, TAB05, TAB06, TAB07, TAB08, TAB09, TAB10, NEW_ETAB_ANC, NEW_ETAB_RENTREE, FRA, ETR, EFFTOT, EFFTOTN, EFFTOTA, ANNEE, CONTRAT_M, SIGLE_M, SECT_M, NAT_M, COM_M, LIB1_M, LIB2_M, ACA_M, MIN_M, CONTRAT_U, SIGLE_U, SECT_U, NAT_U, ...]
Index: []

[0 rows x 119 columns]

In [45]:
#verifier que HCPGE est bien rempli
if 'HCPGE' in list(df.columns):
    print(df.HCPGE.value_counts())

HCPGE
1.0    1348595
0.0      28030
Name: count, dtype: int64

In [46]:
#voir les effectifs sans les doubles comptes
if 'HSIFA' in list(df.columns):
    print(df.EFFTOT.sum()-df.loc[(df['HSIFA']==0.0),'EFFTOT'].sum())
    print(df.loc[(df['HSIFA']==0.0),'EFFTOT'].sum())

2844978.0
189792.0

On applique la fonction importtab, qui va corriger les features une par une de cette année

In [47]:
df_up=importtab(df,CORRECTIFS_dict,CORRECTIFS_dict_esr,corrige_etabli2,corrige_all,rentree_sco,communes)

COM_U
COM_M
ETABLI
DISCIPLI
FORMAT
MINISTER
NATION
CURSUS_LMD
ETABLI2

In [48]:
# test EFFTOT si ils sont toujours egaux sans HSIFA
if 'HSIFA' in list(df.columns):
    print(df_up['HSIFA'].value_counts())
    print(df_up.EFFTOT.sum()-df_up.loc[(df_up['HSIFA']==0.0),'EFFTOT'].sum()==df.EFFTOT.sum()-df.loc[(df['HSIFA']==0.0),'EFFTOT'].sum())

HSIFA
0.0    120485
Name: count, dtype: int64
True

In [49]:
# test si nouveaux formats cette année
[x for x in list(df_up.FORMAT.drop_duplicates()) if x not in list(pd.DataFrame(CORRECTIFS_dict_esr['FORMAT'])['FORMAT'].drop_duplicates())]

[]

In [50]:
df_up.loc[df_up.FORMAT=='']

Empty DataFrame
Columns: [ANNEE, DEGETU, DIPLOM, RENTREE, ENQ, MIN_U, MINISTER, SECT, COMPOS, NAT_U, SIGLE_U, LIB1_U, LIB2_U, COM_U, FINECOLE, ETABLI, ETABLI2, SIGLE_M, LIB1_M, LIB2_M, COM_M, SPECIUT, EFFTOT, EFFTOTN, DC, LMDDONT, LMDDONTBIS, DNDU, DISCIPLI, CURSUS_LMD, FILIERE, ETABLISSEMENT, UNIV, HSIFA, EFFECTIF_SANS_DOUBLE_COMPTE, HCPGE, SEXE, NATION, FORMAT]
Index: []

[0 rows x 39 columns]

In [51]:
df_up.loc[df_up.FORMAT=='None']

Empty DataFrame
Columns: [ANNEE, DEGETU, DIPLOM, RENTREE, ENQ, MIN_U, MINISTER, SECT, COMPOS, NAT_U, SIGLE_U, LIB1_U, LIB2_U, COM_U, FINECOLE, ETABLI, ETABLI2, SIGLE_M, LIB1_M, LIB2_M, COM_M, SPECIUT, EFFTOT, EFFTOTN, DC, LMDDONT, LMDDONTBIS, DNDU, DISCIPLI, CURSUS_LMD, FILIERE, ETABLISSEMENT, UNIV, HSIFA, EFFECTIF_SANS_DOUBLE_COMPTE, HCPGE, SEXE, NATION, FORMAT]
Index: []

[0 rows x 39 columns]

In [52]:
df_up[['ANNEE','COMPOS', 'COM_U', 'ETABLI', 'COM_M']].to_json(f"./POST_IMPORTTAB/atlas{str(rentree_sco)}.json")

In [53]:
#fonction gentab

In [54]:
df_up2= gentab(df_up, rentree_sco, CORRECTIFS_dict, CORRECTIFS_dict_esr, corrige_rgp2, corrige_rgp3, corrige_op_ing,communes)

RGP2
RGP3
OP_ING

On regarde si les effectifs des apprentis sont présents

In [55]:
if 'EFF_STS_APP' in df_up2.columns:
    print(df_up2.EFF_STS_APP.value_counts())

EFF_STS_APP
0      53922
1       1457
2        912
3        725
4        589
       ...
211        1
343        1
290        1
355        1
309        1
Name: count, Length: 200, dtype: Int64

Pour chaque année, on enregistre les données traitées

In [56]:
df_up2.to_json(f"./POST_GENTAB/atlas{str(rentree_sco)}.json")

In [57]:
df_up.columns

Index(['ANNEE', 'DEGETU', 'DIPLOM', 'RENTREE', 'ENQ', 'MIN_U', 'MINISTER',
       'SECT', 'COMPOS', 'NAT_U', 'SIGLE_U', 'LIB1_U', 'LIB2_U', 'COM_U',
       'FINECOLE', 'ETABLI', 'ETABLI2', 'SIGLE_M', 'LIB1_M', 'LIB2_M', 'COM_M',
       'SPECIUT', 'EFFTOT', 'EFFTOTN', 'DC', 'LMDDONT', 'LMDDONTBIS', 'DNDU',
       'DISCIPLI', 'CURSUS_LMD', 'FILIERE', 'ETABLISSEMENT', 'UNIV', 'HSIFA',
       'EFFECTIF_SANS_DOUBLE_COMPTE', 'HCPGE', 'SEXE', 'NATION', 'FORMAT',
       'EFFSDC', 'EFF_STS_APP', 'memeCOM'],
      dtype='object')

In [29]:
#checker la variable finecole (finness) pour les paramedicale "soc", ou checker paysage => pour completer la table COM_M(etabli) et COM_U(compos)
df_up2[df_up2.COM_CODE=='nan']

Empty DataFrame
Columns: [RENTREE, ENQ, MINISTER, SECT, COMPOS, NAT_U, SIGLE_U, LIB1_U, LIB2_U, COM_CODE, COM_NOM, COM_CODE1, COM_NOM1, COM_CODE2, COM_NOM2, UUCR_ID, UUCR_NOM, EPCI_ID, DEP_ID, DEP_NUM_NOM, ACA_ID, ACA_NOM, REG_ID, REG_NOM, REGRGP_NOM, REG_ID_OLD, REG_NOM_OLD, FINECOLE, ETABLI, COM_CODE_ETAB, SIGLE_M, LIB1_M, LIB2_M, UUCR_ID_ETAB, DEP_ID_ETAB, ETABLI2, FORMAT, SPECIUT, LIBELL_, RGP, RGP2, RGP3, RGP4, ING, IUT, INSPE, TOTAL, LMDDONT, LMDDONTBIS, DNDU, DISCIPLI, CURSUS_LMD, FILIERE, ETABLISSEMENT, UNIV, SEXE, DEGETU, memeCOM, memeUUCR, EFFTOT, EFFSDC, EFF_STS_APP, ID]
Index: []

[0 rows x 63 columns]

In [ ]:
#df[df.COMPOS=='830F0100'].FINECOLE

In [ ]:
#df[df.COMPOS=='226P0003'].COM_U #COM_M

In [ ]:
communes=communes[communes.COM_CODE_ACTUEL!='']

In [ ]:
from dotenv import load_dotenv
from io import BytesIO
import os
import numpy as np
import pandas as pd
import requests

load_dotenv()  

GRIST_KEY = os.getenv("GRIST_KEY")

In [ ]:
#pour retrouver les code com grace au finness
#communes[communes.COM_NOM_MAJ_COURT=='CUERS']

In [ ]:
communes2=communes[['COM_CODE','COM_CODE_ACTUEL']]
communes2=communes[communes.COM_CODE_ACTUEL!='']

In [ ]:
df_up2[df_up2.COM_CODE.apply(lambda x: x in list(communes2.COM_CODE))]

In [ ]:
#tests RGP3 
df_up2[df_up2.ETABLI=='0313124C']