In [1]:
#importer les packages
import pandas as pd
from dotenv import load_dotenv
from io import BytesIO
import os
import numpy as np
import pandas as pd
import requests
from tqdm.notebook import tqdm
tqdm.pandas()

from utils.correcting_features import corrige_all, corrige_etabli2, corrige_rgp2, corrige_rgp3, corrige_op_ing
from utils.load_corrections import get_all_correctifs_from_google, load_all_correctifs
from utils.traitements import importtab, gentab

In [2]:
# ATTENTION, avant de commencer, s'assurer d'avoir un dossier "INPUT" 
# avec les données au format parquet pour chaque année et un dossier
# POST_GENTAB pour acceuillir les données traitées (attention c'est assez volumineux)

# Modifier la page format du googlesheet si il y a de nouveaux formats cette année
# Modifier également la page D_EPE du googlesheet ESR pour ajouter les EPE de la nouvelle année

In [3]:
DATA_PATH=os.getcwd()

In [4]:
url_atlas='https://docs.google.com/spreadsheet/ccc?key=11NFXSIg6gQMCsMa8zWQQyypvvYBEmfyJfF2yytXqgMk&output=xls'
url_esr='https://docs.google.com/spreadsheet/ccc?key=1FwPq5Qw7Gbgj_sBD6Za4dfDDk6ydozQ99TyRjLkW5d8&output=xls'

VARS_atlas=['COM_U','COM_M', 'ETABLI', 'MINISTER', 'DC', 'NATION', 'ETABLI2', 'FORMAT','CURSUS_LMD', 'DISCIPLI','RGP2', 'RGP3','OP_ING','SECRET']
VARS_esr=['O_DUTBUT','J_LMDDONT','DISCIPLINES_SISE','FORMAT','D_EPE','C_ETABLISSEMENTS']

Charger les données des googlesheets depuis google en local au format .json dans le dossier (pas besoin de le faire à chaque fois, à faire si c'est la première fois OU lors d'une modification sur le.s googlesheet.s)

In [5]:
load_dotenv()  

GRIST_KEY = os.getenv("GRIST_KEY")

#URL et headers pour l'API Grist
grist_url = "https://grist.numerique.gouv.fr/api/docs/aoAbiYjvgr2aw1Pez2s2wj/download/xlsx?header=colId"
headers = {
    "Authorization": f"Bearer {GRIST_KEY}"
}
response = requests.get(grist_url, headers=headers)
response.raise_for_status()  # Vérifie les erreurs HTTP

with BytesIO(response.content) as excel_data:
    communes = pd.read_excel(excel_data, sheet_name=['Commune'], dtype=str, na_filter=False).get("Commune")

In [6]:
#get_all_correctifs_from_google(url_atlas,VARS_atlas,'_atlas')
#get_all_correctifs_from_google(url_esr,VARS_esr,'_esr')

Charger les 2 googlessheets dans le notebook

In [7]:
CORRECTIFS_dict_esr = load_all_correctifs('_esr')
CORRECTIFS_dict = load_all_correctifs('_atlas')

In [8]:
formats=pd.DataFrame(CORRECTIFS_dict_esr['FORMAT']).drop_duplicates()

On charge bien la rentrée scolaire de l'année en cours

In [9]:
rentree_sco=2002

On charge les données correspondantes

In [10]:
df=pd.read_parquet(f"./INPUT/ts{str(rentree_sco)[2:]}d_tot.parquet", engine='fastparquet')

In [11]:
df.columns=[x.upper() for x in df.columns]

In [12]:
df[pd.isna(df.FORMAT)]
#df.loc[(pd.isna(df.FORMAT))&(df.ETABLI=='9830445S'),'FORMAT'] = 'autr'

Empty DataFrame
Columns: [SIGLE_U, SECT_U, NAT_U, COM_U, LIB1_U, LIB2_U, ACA_U, SIGLE_M, SECT_M, NAT_M, COM_M, LIB1_M, LIB2_M, ACA_M, ACAM, ETABLI, COMPOS, NATION, SEXE, SECTEUR, GROUPE, FR_ETR_R, FR_ETR_D, CYCLE, TYP_DIPL, DISCIPLI, SECTDIS, DIPLOM, ENQ, FORMAT, UNIPUR, EFFTOT, UNIING, UNIPRE, UNINFI, UNIGD, IUTSEC, IUTTER, UTING, UTPRE, UTAUT, INPING, INPPRE, INPNFI, INPAUT, UNIBLS, EFFTOTN, MINISTER, MEFBCP11, SPEC, CPGESC, CPGELI, CPGEEC, STSPR, STSSE, DCESF, DPECF, NIVPR, NIVSE, DMAPR, DMASE, DSAAPR, DSAASE, DNTSPR, DNTSSE, DECF, DESCF, FCP4, FCP3PR, FCP3SE, PDP, CPGEN, NIVN, STSN, DNTSN, FCP3N, DMAN, DSAAN, DPECFN, DECFN, DESCFN, FCP4N, PDPN, CPGEAG, STSAG, ART, TYPE, INGU, INGUT, INGINP, INGO, CPIU, CPIUT, CPIINP, CPIO, MASU, MASUT, MASINP, MASO, IUFM, ...]
Index: []

[0 rows x 124 columns]

In [13]:
df[pd.isna(df.ETABLI)]

Empty DataFrame
Columns: [SIGLE_U, SECT_U, NAT_U, COM_U, LIB1_U, LIB2_U, ACA_U, SIGLE_M, SECT_M, NAT_M, COM_M, LIB1_M, LIB2_M, ACA_M, ACAM, ETABLI, COMPOS, NATION, SEXE, SECTEUR, GROUPE, FR_ETR_R, FR_ETR_D, CYCLE, TYP_DIPL, DISCIPLI, SECTDIS, DIPLOM, ENQ, FORMAT, UNIPUR, EFFTOT, UNIING, UNIPRE, UNINFI, UNIGD, IUTSEC, IUTTER, UTING, UTPRE, UTAUT, INPING, INPPRE, INPNFI, INPAUT, UNIBLS, EFFTOTN, MINISTER, MEFBCP11, SPEC, CPGESC, CPGELI, CPGEEC, STSPR, STSSE, DCESF, DPECF, NIVPR, NIVSE, DMAPR, DMASE, DSAAPR, DSAASE, DNTSPR, DNTSSE, DECF, DESCF, FCP4, FCP3PR, FCP3SE, PDP, CPGEN, NIVN, STSN, DNTSN, FCP3N, DMAN, DSAAN, DPECFN, DECFN, DESCFN, FCP4N, PDPN, CPGEAG, STSAG, ART, TYPE, INGU, INGUT, INGINP, INGO, CPIU, CPIUT, CPIINP, CPIO, MASU, MASUT, MASINP, MASO, IUFM, ...]
Index: []

[0 rows x 124 columns]

In [14]:
df[pd.isna(df.COMPOS)]

Empty DataFrame
Columns: [SIGLE_U, SECT_U, NAT_U, COM_U, LIB1_U, LIB2_U, ACA_U, SIGLE_M, SECT_M, NAT_M, COM_M, LIB1_M, LIB2_M, ACA_M, ACAM, ETABLI, COMPOS, NATION, SEXE, SECTEUR, GROUPE, FR_ETR_R, FR_ETR_D, CYCLE, TYP_DIPL, DISCIPLI, SECTDIS, DIPLOM, ENQ, FORMAT, UNIPUR, EFFTOT, UNIING, UNIPRE, UNINFI, UNIGD, IUTSEC, IUTTER, UTING, UTPRE, UTAUT, INPING, INPPRE, INPNFI, INPAUT, UNIBLS, EFFTOTN, MINISTER, MEFBCP11, SPEC, CPGESC, CPGELI, CPGEEC, STSPR, STSSE, DCESF, DPECF, NIVPR, NIVSE, DMAPR, DMASE, DSAAPR, DSAASE, DNTSPR, DNTSSE, DECF, DESCF, FCP4, FCP3PR, FCP3SE, PDP, CPGEN, NIVN, STSN, DNTSN, FCP3N, DMAN, DSAAN, DPECFN, DECFN, DESCFN, FCP4N, PDPN, CPGEAG, STSAG, ART, TYPE, INGU, INGUT, INGINP, INGO, CPIU, CPIUT, CPIINP, CPIO, MASU, MASUT, MASINP, MASO, IUFM, ...]
Index: []

[0 rows x 124 columns]

In [15]:
df[pd.isna(df.SEXE)]

Empty DataFrame
Columns: [SIGLE_U, SECT_U, NAT_U, COM_U, LIB1_U, LIB2_U, ACA_U, SIGLE_M, SECT_M, NAT_M, COM_M, LIB1_M, LIB2_M, ACA_M, ACAM, ETABLI, COMPOS, NATION, SEXE, SECTEUR, GROUPE, FR_ETR_R, FR_ETR_D, CYCLE, TYP_DIPL, DISCIPLI, SECTDIS, DIPLOM, ENQ, FORMAT, UNIPUR, EFFTOT, UNIING, UNIPRE, UNINFI, UNIGD, IUTSEC, IUTTER, UTING, UTPRE, UTAUT, INPING, INPPRE, INPNFI, INPAUT, UNIBLS, EFFTOTN, MINISTER, MEFBCP11, SPEC, CPGESC, CPGELI, CPGEEC, STSPR, STSSE, DCESF, DPECF, NIVPR, NIVSE, DMAPR, DMASE, DSAAPR, DSAASE, DNTSPR, DNTSSE, DECF, DESCF, FCP4, FCP3PR, FCP3SE, PDP, CPGEN, NIVN, STSN, DNTSN, FCP3N, DMAN, DSAAN, DPECFN, DECFN, DESCFN, FCP4N, PDPN, CPGEAG, STSAG, ART, TYPE, INGU, INGUT, INGINP, INGO, CPIU, CPIUT, CPIINP, CPIO, MASU, MASUT, MASINP, MASO, IUFM, ...]
Index: []

[0 rows x 124 columns]

In [16]:
#verifier que HCPGE est bien rempli
if 'HCPGE' in list(df.columns):
    print(df.HCPGE.value_counts())

In [17]:
#voir les effectifs sans les doubles comptes
if 'HSIFA' in list(df.columns):
    print(df.EFFTOT.sum()-df.loc[(df['HSIFA']==0.0),'EFFTOT'].sum())
    print(df.loc[(df['HSIFA']==0.0),'EFFTOT'].sum())

On applique la fonction importtab, qui va corriger les features une par une de cette année

In [18]:
df_up=importtab(df,CORRECTIFS_dict,CORRECTIFS_dict_esr,corrige_etabli2,corrige_all,rentree_sco,communes)

COM_U
COM_M
ETABLI
DISCIPLI
FORMAT
MINISTER
NATION
CURSUS_LMD

c:\Users\haallat\Documents\atlas-opendata\utils\correcting_features.py:184: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'L' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[((df[VAR] == '')|(pd.isna(df[VAR])) |(df[VAR]==None)) & (df['ETABLI']==c['ETABLI']) & (df['RENTREE']==c['ANNEE']), VAR]=c['OUT']

ETABLI2

c:\Users\haallat\Documents\atlas-opendata\utils\traitements.py:120: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'commerce' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df['COMPOS'] == '9830642F', 'ETABLISSEMENT'] = 'commerce'

In [19]:
# test EFFTOT si ils sont toujours egaux sans HSIFA
if 'HSIFA' in list(df.columns):
    print(df_up['HSIFA'].value_counts())
    print(df_up.EFFTOT.sum()-df_up.loc[(df_up['HSIFA']==0.0),'EFFTOT'].sum()==df.EFFTOT.sum()-df.loc[(df['HSIFA']==0.0),'EFFTOT'].sum())

Series([], Name: count, dtype: int64)
False

In [20]:
# test si nouveaux formats cette année
[x for x in list(df_up.FORMAT.drop_duplicates()) if x not in list(pd.DataFrame(CORRECTIFS_dict_esr['FORMAT'])['FORMAT'].drop_duplicates())]

[]

In [21]:
df_up.loc[df_up.FORMAT=='']

Empty DataFrame
Columns: [ANNEE, DIPLOM, RENTREE, ENQ, MINISTER, SECT, COMPOS, NAT_U, SIGLE_U, LIB1_U, LIB2_U, COM_U, FINECOLE, ETABLI, ETABLI2, SIGLE_M, LIB1_M, LIB2_M, COM_M, SPECIUT, EFFTOT, EFFTOTN, DC, LMDDONT, LMDDONTBIS, DNDU, DISCIPLI, CURSUS_LMD, FILIERE, ETABLISSEMENT, UNIV, HSIFA, EFFECTIF_SANS_DOUBLE_COMPTE, HCPGE, SEXE, NATION, FORMAT]
Index: []

[0 rows x 37 columns]

In [22]:
df_up.loc[df_up.FORMAT=='None']

Empty DataFrame
Columns: [ANNEE, DIPLOM, RENTREE, ENQ, MINISTER, SECT, COMPOS, NAT_U, SIGLE_U, LIB1_U, LIB2_U, COM_U, FINECOLE, ETABLI, ETABLI2, SIGLE_M, LIB1_M, LIB2_M, COM_M, SPECIUT, EFFTOT, EFFTOTN, DC, LMDDONT, LMDDONTBIS, DNDU, DISCIPLI, CURSUS_LMD, FILIERE, ETABLISSEMENT, UNIV, HSIFA, EFFECTIF_SANS_DOUBLE_COMPTE, HCPGE, SEXE, NATION, FORMAT]
Index: []

[0 rows x 37 columns]

In [23]:
df_up[['ANNEE','COMPOS', 'COM_U', 'ETABLI', 'COM_M']].to_json(f"./POST_IMPORTTAB/atlas{str(rentree_sco)}.json")

In [36]:
df_up2[(df_up2.RGP3=='GE')&(df_up2.COM_CODE=='26362')]

,RENTREE,ENQ,MINISTER,SECT,COMPOS,NAT_U,SIGLE_U,LIB1_U,LIB2_U,COM_CODE,...,FILIERE,ETABLISSEMENT,UNIV,SEXE,memeCOM,memeUUCR,EFFTOT,EFFSDC,EFF_STS_APP,ID
5762,2002,sise,,PU,0261324Y,553,ESISAR,ESISAR VALENCE,INP GRENOBLE,26362,...,nan,nan,nan,1,False,False,228,0,0,R84
5763,2002,sise,,PU,0261324Y,553,ESISAR,ESISAR VALENCE,INP GRENOBLE,26362,...,nan,nan,nan,2,False,False,33,0,0,R84

In [ ]:
#fonction gentab

In [26]:
df_up2= gentab(df_up, rentree_sco, CORRECTIFS_dict, CORRECTIFS_dict_esr, corrige_rgp2, corrige_rgp3, corrige_op_ing,communes)

RGP2
RGP3
OP_ING

On regarde si les effectifs des apprentis sont présents

In [27]:
if 'EFF_STS_APP' in df_up2.columns:
    print(df_up2.EFF_STS_APP.value_counts())

EFF_STS_APP
0    27051
Name: count, dtype: Int64

Pour chaque année, on enregistre les données traitées

In [28]:
df_up2.to_json(f"./POST_GENTAB/atlas{str(rentree_sco)}.json")

In [29]:
#checker la variable finecole (finness) pour les paramedicale "soc", ou checker paysage => pour completer la table COM_M(etabli) et COM_U(compos)
df_up2[df_up2.COM_CODE=='nan']

Empty DataFrame
Columns: [RENTREE, ENQ, MINISTER, SECT, COMPOS, NAT_U, SIGLE_U, LIB1_U, LIB2_U, COM_CODE, COM_NOM, COM_CODE1, COM_NOM1, COM_CODE2, COM_NOM2, UUCR_ID, UUCR_NOM, EPCI_ID, DEP_ID, DEP_NUM_NOM, ACA_ID, ACA_NOM, REG_ID, REG_NOM, REGRGP_NOM, REG_ID_OLD, REG_NOM_OLD, FINECOLE, ETABLI, COM_CODE_ETAB, SIGLE_M, LIB1_M, LIB2_M, UUCR_ID_ETAB, DEP_ID_ETAB, ETABLI2, FORMAT, SPECIUT, LIBELL_, RGP, RGP2, RGP3, RGP4, ING, IUT, INSPE, TOTAL, LMDDONT, LMDDONTBIS, DNDU, DISCIPLI, CURSUS_LMD, FILIERE, ETABLISSEMENT, UNIV, SEXE, memeCOM, memeUUCR, EFFTOT, EFFSDC, EFF_STS_APP, ID]
Index: []

[0 rows x 62 columns]

In [30]:
#df[df.COMPOS=='830F0100'].FINECOLE

In [31]:
#df[df.COMPOS=='226P0003'].COM_U #COM_M

In [32]:
communes=communes[communes.COM_CODE_ACTUEL!='']

In [33]:
from dotenv import load_dotenv
from io import BytesIO
import os
import numpy as np
import pandas as pd
import requests

load_dotenv()  

GRIST_KEY = os.getenv("GRIST_KEY")

In [ ]:
#pour retrouver les code com grace au finness
#communes[communes.COM_NOM_MAJ_COURT=='CUERS']

In [ ]:
communes2=communes[['COM_CODE','COM_CODE_ACTUEL']]
communes2=communes[communes.COM_CODE_ACTUEL!='']

In [ ]:
df_up2[df_up2.COM_CODE.apply(lambda x: x in list(communes2.COM_CODE))]

In [ ]:
#tests RGP3 
df_up2[df_up2.ETABLI=='0313124C']