In [1]:
#importer les packages
import os
import pandas as pd
from dotenv import load_dotenv
from io import BytesIO
import os
import numpy as np
import pandas as pd
import requests
from tqdm.notebook import tqdm
tqdm.pandas()

from utils.correcting_features import corrige_all, corrige_etabli2, corrige_rgp2, corrige_rgp3, corrige_op_ing
from utils.load_corrections import get_all_correctifs_from_google, load_all_correctifs
from utils.traitements import importtab, gentab

In [2]:
# ATTENTION, avant de commencer, s'assurer d'avoir un dossier "INPUT" 
# avec les données au format parquet pour chaque année et un dossier
# POST_GENTAB pour acceuillir les données traitées (attention c'est assez volumineux)

# Modifier la page format du googlesheet si il y a de nouveaux formats cette année
# Modifier également la page D_EPE du googlesheet ESR pour ajouter les EPE de la nouvelle année

In [3]:
DATA_PATH=os.getcwd()

In [4]:
url_atlas='https://docs.google.com/spreadsheet/ccc?key=11NFXSIg6gQMCsMa8zWQQyypvvYBEmfyJfF2yytXqgMk&output=xls'
url_esr='https://docs.google.com/spreadsheet/ccc?key=1FwPq5Qw7Gbgj_sBD6Za4dfDDk6ydozQ99TyRjLkW5d8&output=xls'

VARS_atlas=['COM_U','COM_M', 'ETABLI', 'MINISTER', 'DC', 'NATION', 'ETABLI2', 'FORMAT','CURSUS_LMD', 'DISCIPLI','RGP2', 'RGP3','OP_ING','SECRET']
VARS_esr=['O_DUTBUT','J_LMDDONT','DISCIPLINES_SISE','FORMAT','D_EPE','C_ETABLISSEMENTS']

Charger les données des googlesheets depuis google en local au format .json dans le dossier (pas besoin de le faire à chaque fois, à faire si c'est la première fois OU lors d'une modification sur le.s googlesheet.s)

In [5]:
load_dotenv()  

GRIST_KEY = os.getenv("GRIST_KEY")

#URL et headers pour l'API Grist
grist_url = "https://grist.numerique.gouv.fr/api/docs/aoAbiYjvgr2aw1Pez2s2wj/download/xlsx?header=colId"
headers = {
    "Authorization": f"Bearer {GRIST_KEY}"
}
response = requests.get(grist_url, headers=headers)
response.raise_for_status()  # Vérifie les erreurs HTTP

with BytesIO(response.content) as excel_data:
    communes = pd.read_excel(excel_data, sheet_name=['Commune'], dtype=str, na_filter=False).get("Commune")

In [6]:
#get_all_correctifs_from_google(url_atlas,VARS_atlas,'_atlas')
#get_all_correctifs_from_google(url_esr,VARS_esr,'_esr')

Charger les 2 googlessheets dans le notebook

In [7]:
CORRECTIFS_dict_esr = load_all_correctifs('_esr')
CORRECTIFS_dict = load_all_correctifs('_atlas')

In [8]:
formats=pd.DataFrame(CORRECTIFS_dict_esr['FORMAT']).drop_duplicates()

On charge bien la rentrée scolaire de l'année en cours

In [9]:
rentree_sco=2025

On charge les données correspondantes

In [10]:
df=pd.read_parquet(f"./INPUT/ts{str(rentree_sco)[2:]}p_tot.parquet", engine='fastparquet')

In [11]:
df.columns=[x.upper() for x in df.columns]

In [12]:
df[pd.isna(df.FORMAT)]
#df.loc[(pd.isna(df.FORMAT))&(df.ETABLI=='9830445S'),'FORMAT'] = 'autr'

Empty DataFrame
Columns: [SECTEUR, FORMAT, ENQ, NATION, ETABLI, COMPOS, NATR, SEXE, GROUPE, TYP_DIPL, DISCIPLI, SECTDIS, DIPLOM, REGIME, CURSUS_LMD, UNIV, FLAG_MEEF, HCPGE, DBCOMPTE, BAC_RGRP, ACABAC, ANBAC, PCS, ETABLI_DIFFUSION, AGE, ECHANG, DEGETU, FLAG_REGROUPEMENT, IMPUTATION, INDIC_COMUE, OPPOS, CONV, CURPAR, COMUE_RATT, TYPE, ETABLI_RATT, MEFBCP11, MEFST11, HSIFA, DIPLOME_STSAP, FR_ETR_R, FR_ETR_D, ADRESSE, ADRESSE_UAI, CONTRAT, DENOMINATION_PRINCIPALE_UAI, DEP, DISC, FINECOLE, LIBELLE ROUTAGE, LOCALITE_ACHEMINEMENT_UAI, MINISTERE_TUTELLE, NIVEAU_UAI, NIVFORM, NOMECOLE, PATRONYME_UAI, NATIO, LIG, NIVEAU_U, TYPE_LIB, Z_COL1, Z_COL2, Z_COL3, Z_COL4, Z_COL5, Z_COL6, Z_COL7, Z_COL8, Z_COL9, Z_COL10, Z_COL11, Z_COL12, TAB02, TAB04, TAB05, TAB06, TAB07, TAB08, TAB09, TAB10, NEW_ETAB_ANC, NEW_ETAB_RENTREE, FRA, ETR, EFFTOT, EFFTOTN, EFFTOTA, ANNEE, CONTRAT_M, SIGLE_M, SECT_M, NAT_M, COM_M, LIB1_M, LIB2_M, ACA_M, MIN_M, CONTRAT_U, SIGLE_U, SECT_U, ...]
Index: []

[0 rows x 121 columns]

In [13]:
df[pd.isna(df.ETABLI)]

Empty DataFrame
Columns: [SECTEUR, FORMAT, ENQ, NATION, ETABLI, COMPOS, NATR, SEXE, GROUPE, TYP_DIPL, DISCIPLI, SECTDIS, DIPLOM, REGIME, CURSUS_LMD, UNIV, FLAG_MEEF, HCPGE, DBCOMPTE, BAC_RGRP, ACABAC, ANBAC, PCS, ETABLI_DIFFUSION, AGE, ECHANG, DEGETU, FLAG_REGROUPEMENT, IMPUTATION, INDIC_COMUE, OPPOS, CONV, CURPAR, COMUE_RATT, TYPE, ETABLI_RATT, MEFBCP11, MEFST11, HSIFA, DIPLOME_STSAP, FR_ETR_R, FR_ETR_D, ADRESSE, ADRESSE_UAI, CONTRAT, DENOMINATION_PRINCIPALE_UAI, DEP, DISC, FINECOLE, LIBELLE ROUTAGE, LOCALITE_ACHEMINEMENT_UAI, MINISTERE_TUTELLE, NIVEAU_UAI, NIVFORM, NOMECOLE, PATRONYME_UAI, NATIO, LIG, NIVEAU_U, TYPE_LIB, Z_COL1, Z_COL2, Z_COL3, Z_COL4, Z_COL5, Z_COL6, Z_COL7, Z_COL8, Z_COL9, Z_COL10, Z_COL11, Z_COL12, TAB02, TAB04, TAB05, TAB06, TAB07, TAB08, TAB09, TAB10, NEW_ETAB_ANC, NEW_ETAB_RENTREE, FRA, ETR, EFFTOT, EFFTOTN, EFFTOTA, ANNEE, CONTRAT_M, SIGLE_M, SECT_M, NAT_M, COM_M, LIB1_M, LIB2_M, ACA_M, MIN_M, CONTRAT_U, SIGLE_U, SECT_U, ...]
Index: []

[0 rows x 121 columns]

In [14]:
df[pd.isna(df.COMPOS)]

Empty DataFrame
Columns: [SECTEUR, FORMAT, ENQ, NATION, ETABLI, COMPOS, NATR, SEXE, GROUPE, TYP_DIPL, DISCIPLI, SECTDIS, DIPLOM, REGIME, CURSUS_LMD, UNIV, FLAG_MEEF, HCPGE, DBCOMPTE, BAC_RGRP, ACABAC, ANBAC, PCS, ETABLI_DIFFUSION, AGE, ECHANG, DEGETU, FLAG_REGROUPEMENT, IMPUTATION, INDIC_COMUE, OPPOS, CONV, CURPAR, COMUE_RATT, TYPE, ETABLI_RATT, MEFBCP11, MEFST11, HSIFA, DIPLOME_STSAP, FR_ETR_R, FR_ETR_D, ADRESSE, ADRESSE_UAI, CONTRAT, DENOMINATION_PRINCIPALE_UAI, DEP, DISC, FINECOLE, LIBELLE ROUTAGE, LOCALITE_ACHEMINEMENT_UAI, MINISTERE_TUTELLE, NIVEAU_UAI, NIVFORM, NOMECOLE, PATRONYME_UAI, NATIO, LIG, NIVEAU_U, TYPE_LIB, Z_COL1, Z_COL2, Z_COL3, Z_COL4, Z_COL5, Z_COL6, Z_COL7, Z_COL8, Z_COL9, Z_COL10, Z_COL11, Z_COL12, TAB02, TAB04, TAB05, TAB06, TAB07, TAB08, TAB09, TAB10, NEW_ETAB_ANC, NEW_ETAB_RENTREE, FRA, ETR, EFFTOT, EFFTOTN, EFFTOTA, ANNEE, CONTRAT_M, SIGLE_M, SECT_M, NAT_M, COM_M, LIB1_M, LIB2_M, ACA_M, MIN_M, CONTRAT_U, SIGLE_U, SECT_U, ...]
Index: []

[0 rows x 121 columns]

In [15]:
df[pd.isna(df.SEXE)]

Empty DataFrame
Columns: [SECTEUR, FORMAT, ENQ, NATION, ETABLI, COMPOS, NATR, SEXE, GROUPE, TYP_DIPL, DISCIPLI, SECTDIS, DIPLOM, REGIME, CURSUS_LMD, UNIV, FLAG_MEEF, HCPGE, DBCOMPTE, BAC_RGRP, ACABAC, ANBAC, PCS, ETABLI_DIFFUSION, AGE, ECHANG, DEGETU, FLAG_REGROUPEMENT, IMPUTATION, INDIC_COMUE, OPPOS, CONV, CURPAR, COMUE_RATT, TYPE, ETABLI_RATT, MEFBCP11, MEFST11, HSIFA, DIPLOME_STSAP, FR_ETR_R, FR_ETR_D, ADRESSE, ADRESSE_UAI, CONTRAT, DENOMINATION_PRINCIPALE_UAI, DEP, DISC, FINECOLE, LIBELLE ROUTAGE, LOCALITE_ACHEMINEMENT_UAI, MINISTERE_TUTELLE, NIVEAU_UAI, NIVFORM, NOMECOLE, PATRONYME_UAI, NATIO, LIG, NIVEAU_U, TYPE_LIB, Z_COL1, Z_COL2, Z_COL3, Z_COL4, Z_COL5, Z_COL6, Z_COL7, Z_COL8, Z_COL9, Z_COL10, Z_COL11, Z_COL12, TAB02, TAB04, TAB05, TAB06, TAB07, TAB08, TAB09, TAB10, NEW_ETAB_ANC, NEW_ETAB_RENTREE, FRA, ETR, EFFTOT, EFFTOTN, EFFTOTA, ANNEE, CONTRAT_M, SIGLE_M, SECT_M, NAT_M, COM_M, LIB1_M, LIB2_M, ACA_M, MIN_M, CONTRAT_U, SIGLE_U, SECT_U, ...]
Index: []

[0 rows x 121 columns]

In [16]:
#verifier que HCPGE est bien rempli
if 'HCPGE' in list(df.columns):
    print(df.HCPGE.value_counts())

HCPGE
1.0    1653751
0.0      28114
Name: count, dtype: int64

In [17]:
#voir les effectifs sans les doubles comptes
if 'HSIFA' in list(df.columns):
    print(df.EFFTOT.sum()-df.loc[(df['HSIFA']==0.0),'EFFTOT'].sum())
    print(df.loc[(df['HSIFA']==0.0),'EFFTOT'].sum())

2948753.0
172091.0

On applique la fonction importtab, qui va corriger les features une par une de cette année

In [ ]:
df_up=importtab(df,CORRECTIFS_dict,CORRECTIFS_dict_esr,corrige_etabli2,corrige_all,rentree_sco,communes)

c:\Users\haallat\Documents\atlas-opendata\utils\traitements.py:53: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'DU' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df['TYP_DIPL'].isin(["01","02","04","05","06","07","08","09","17","UA","UB","UC","UD","UE","UF","UG","UI","UJ","UO","UR","US","UT","UU","UV","UY","XF"]),'DNDU']='DU'

COM_U
COM_M

In [ ]:
# test EFFTOT si ils sont toujours egaux sans HSIFA
if 'HSIFA' in list(df.columns):
    print(df_up['HSIFA'].value_counts())
    print(df_up.EFFTOT.sum()-df_up.loc[(df_up['HSIFA']==0.0),'EFFTOT'].sum()==df.EFFTOT.sum()-df.loc[(df['HSIFA']==0.0),'EFFTOT'].sum())

In [ ]:
# test si nouveaux formats cette année
[x for x in list(df_up.FORMAT.drop_duplicates()) if x not in list(pd.DataFrame(CORRECTIFS_dict_esr['FORMAT'])['FORMAT'].drop_duplicates())]

In [ ]:
df_up.loc[df_up.FORMAT=='']

In [ ]:
df_up.loc[df_up.FORMAT=='None']

In [ ]:
#fonction gentab

In [ ]:
df_up2= gentab(df_up, rentree_sco, CORRECTIFS_dict, CORRECTIFS_dict_esr, corrige_rgp2, corrige_rgp3, corrige_op_ing,communes)

In [ ]:
'DIPLOM' in df_up2.columns

On regarde si les effectifs des apprentis sont présents

In [ ]:
if 'EFF_STS_APP' in df_up2.columns:
    print(df_up2.EFF_STS_APP.value_counts())

Pour chaque année, on enregistre les données traitées

In [ ]:
df_up2.to_json(f"./POST_GENTAB/atlas{str(rentree_sco)}.json")

In [ ]:
df_up.columns

In [ ]:
df_up2[df_up2.COM_CODE=='nan'] #checker la variable finecole (finness) si c'est des codes postaux

In [ ]:
df[df.COMPOS=='1370012U'].COMPOS

In [ ]:
df[df.COMPOS=='1370012U'].COM_M

In [ ]:
df_up2[df_up2.COM_CODE=='nan'].FINECOLE

In [ ]:
from dotenv import load_dotenv
from io import BytesIO
import os
import numpy as np
import pandas as pd
import requests

load_dotenv()  

GRIST_KEY = os.getenv("GRIST_KEY")

In [ ]:
grist_url = "https://grist.numerique.gouv.fr/api/docs/aoAbiYjvgr2aw1Pez2s2wj/download/xlsx?header=colId"
headers = {
    "Authorization": f"Bearer {GRIST_KEY}"
}
response = requests.get(grist_url, headers=headers)
response.raise_for_status()  # Vérifie les erreurs HTTP

with BytesIO(response.content) as excel_data:
    communes = pd.read_excel(excel_data, sheet_name=['Commune'], dtype=str, na_filter=False).get("Commune")

In [ ]:
communes=communes[['COM_CODE','COM_CODE_ACTUEL']]
dict_communes={commune['COM_CODE']:commune['COM_CODE_ACTUEL'] for commune in communes[communes.COM_CODE_ACTUEL!=''].to_dict('records')}

In [ ]:
dict_communes