In [5]:
#importer les packages
import pandas as pd
from datetime import datetime
from tqdm.notebook import tqdm
from dotenv import load_dotenv
from io import BytesIO
import os
import requests
tqdm.pandas()

from utils.load_corrections import load_all_correctifs
from utils.opendata import opendata_atlas
from utils.traitements import remplacer_nan_par_vide

In [6]:
CORRECTIFS_dict_esr = load_all_correctifs('_esr')

In [7]:
load_dotenv()  

GRIST_KEY = os.getenv("GRIST_KEY")

#URL et headers pour l'API Grist
grist_url = "https://grist.numerique.gouv.fr/api/docs/aoAbiYjvgr2aw1Pez2s2wj/download/xlsx?header=colId"
headers = {
    "Authorization": f"Bearer {GRIST_KEY}"
}
response = requests.get(grist_url, headers=headers)
response.raise_for_status()  # Vérifie les erreurs HTTP

with BytesIO(response.content) as excel_data:
    communes = pd.read_excel(excel_data, sheet_name=['Commune'], dtype=str, na_filter=False).get("Commune")

In [8]:
#pour voir si la commune est modifié dans grist
communes[communes.COM_CODE=='62041'][['COM_CODE','COM_CODE_ACTUEL']]

      COM_CODE COM_CODE_ACTUEL
26400    62041

tableau croisé verification commune

In [9]:
#from build_crosstab import build_annual_crosstab_from_atlas_json

#build_annual_crosstab_from_atlas_json(
#    "./POST_IMPORTTAB",
#    "resultat.xlsx",
#    years=range(2001, 2026),
#)

à faire tourner pour chaque année:

In [10]:
rentree_sco='2003'

In [11]:
df=pd.read_json(f"./POST_GENTAB/atlas{rentree_sco}.json")

In [12]:
#on verfifie que tous les codes d'uu sont identifiés
df[df.COM_CODE=='nan']

Empty DataFrame
Columns: [RENTREE, ENQ, MINISTER, SECT, COMPOS, NAT_U, SIGLE_U, LIB1_U, LIB2_U, COM_CODE, COM_NOM, COM_CODE1, COM_NOM1, COM_CODE2, COM_NOM2, UUCR_ID, UUCR_NOM, EPCI_ID, DEP_ID, DEP_NUM_NOM, ACA_ID, ACA_NOM, REG_ID, REG_NOM, REGRGP_NOM, REG_ID_OLD, REG_NOM_OLD, FINECOLE, ETABLI, COM_CODE_ETAB, SIGLE_M, LIB1_M, LIB2_M, UUCR_ID_ETAB, DEP_ID_ETAB, ETABLI2, FORMAT, SPECIUT, LIBELL_, RGP, RGP2, RGP3, RGP4, ING, IUT, INSPE, TOTAL, LMDDONT, LMDDONTBIS, DNDU, DISCIPLI, CURSUS_LMD, FILIERE, ETABLISSEMENT, UNIV, SEXE, memeCOM, memeUUCR, EFFTOT, EFFSDC, EFF_STS_APP, ID]
Index: []

[0 rows x 62 columns]

In [13]:
#on vérifie que les COMPOS ne valent pas les codes communes (drom et com pas grave, 97)
df[df.apply(lambda x:x.COMPOS[:5]==x.COM_CODE ,axis=1)][['COMPOS','COM_CODE']].drop_duplicates()

         COMPOS COM_CODE
1679   9730224F    97302
2491   9730279R    97302
2493   9741101D    97411
2495   9741102E    97411
2649   9741103F    97411
19577  9730269E    97302
20249  9730278P    97302
26355  9741230U    97412

In [14]:
#on verfifie que tous les secteurs sont remplis
df[pd.isna(df.SECT)]

Empty DataFrame
Columns: [RENTREE, ENQ, MINISTER, SECT, COMPOS, NAT_U, SIGLE_U, LIB1_U, LIB2_U, COM_CODE, COM_NOM, COM_CODE1, COM_NOM1, COM_CODE2, COM_NOM2, UUCR_ID, UUCR_NOM, EPCI_ID, DEP_ID, DEP_NUM_NOM, ACA_ID, ACA_NOM, REG_ID, REG_NOM, REGRGP_NOM, REG_ID_OLD, REG_NOM_OLD, FINECOLE, ETABLI, COM_CODE_ETAB, SIGLE_M, LIB1_M, LIB2_M, UUCR_ID_ETAB, DEP_ID_ETAB, ETABLI2, FORMAT, SPECIUT, LIBELL_, RGP, RGP2, RGP3, RGP4, ING, IUT, INSPE, TOTAL, LMDDONT, LMDDONTBIS, DNDU, DISCIPLI, CURSUS_LMD, FILIERE, ETABLISSEMENT, UNIV, SEXE, memeCOM, memeUUCR, EFFTOT, EFFSDC, EFF_STS_APP, ID]
Index: []

[0 rows x 62 columns]

In [15]:
#on verfifie que tous les sexes sont remplis
df[pd.isna(df.SEXE)]

Empty DataFrame
Columns: [RENTREE, ENQ, MINISTER, SECT, COMPOS, NAT_U, SIGLE_U, LIB1_U, LIB2_U, COM_CODE, COM_NOM, COM_CODE1, COM_NOM1, COM_CODE2, COM_NOM2, UUCR_ID, UUCR_NOM, EPCI_ID, DEP_ID, DEP_NUM_NOM, ACA_ID, ACA_NOM, REG_ID, REG_NOM, REGRGP_NOM, REG_ID_OLD, REG_NOM_OLD, FINECOLE, ETABLI, COM_CODE_ETAB, SIGLE_M, LIB1_M, LIB2_M, UUCR_ID_ETAB, DEP_ID_ETAB, ETABLI2, FORMAT, SPECIUT, LIBELL_, RGP, RGP2, RGP3, RGP4, ING, IUT, INSPE, TOTAL, LMDDONT, LMDDONTBIS, DNDU, DISCIPLI, CURSUS_LMD, FILIERE, ETABLISSEMENT, UNIV, SEXE, memeCOM, memeUUCR, EFFTOT, EFFSDC, EFF_STS_APP, ID]
Index: []

[0 rows x 62 columns]

In [16]:
int(df.RENTREE[0])>2014

False

In [17]:
df.columns=[x.upper() for x in df.columns]
df.loc[df['REG_ID']!="R99","PAYS_ID"]="PAYS_100"
df.loc[df['REG_ID']=="R99","PAYS_ID"]="PAYS_999"
df.loc[(df['IUT']=="IUT")&(df['SPECIUT']=="AUTRES"),"IUT2"]="AUTRE"
df.loc[(df['IUT']=="IUT")&(df['SPECIUT']!="AUTRES"),"IUT2"]="DUT"
df.loc[(df['IUT2']=="DUT")&(df['FORMAT'].isin(["iutsec","iutsge","gdiuts"])),"DUT"]="SEC"
df.loc[(df['IUT2']=="DUT")&(df['FORMAT'].isin(["iutter","iuttge","gdiutt"])),"DUT"]="TER"
df.loc[(df['RGP3']=="STS")&(df['FORMAT']=="dcesf"),"STS_ASS"]="dce"
df.loc[(df['RGP3']=="STS")&(df['FORMAT']=="dmapr"),"STS_ASS"]="DMA"
df.loc[(df['RGP3']=="STS")&(df['FORMAT']=="dmase"),"STS_ASS"]="DMA"
df.loc[(df['RGP3']=="STS")&(df['FORMAT']=="nivpr"),"STS_ASS"]="NIV"
df.loc[(df['RGP3']=="STS")&(df['FORMAT']=="nivse"),"STS_ASS"]="NIV"
df.loc[(df['RGP3']=="STS")&(df['FORMAT']=="stsag"),"STS_ASS"]="STS"
df.loc[(df['RGP3']=="STS")&(df['FORMAT']=="stspr"),"STS_ASS"]="STS"
df.loc[(df['RGP3']=="STS")&(df['FORMAT']=="stsse"),"STS_ASS"]="STS"
df.loc[(df['FORMAT']=="cpgeag"),"FORMAT"]="cpgesc"
df.loc[df['RGP3']=='UNIV','UNIV']='UNIV'
df.loc[~df['RGP3'].isin(["ENS","GE","INP","IUFM","UNIV","UT"]),'ETABLI']=""
df.loc[~df['RGP3'].isin(["ENS","GE","INP","IUFM","UNIV","UT"]),'DISCIPLI']=""
df.loc[~df['RGP3'].isin(["ENS","GE","INP","IUFM","UNIV","UT"]),'CURSUS_LMD']=""
df.loc[df['RENTREE'].apply(lambda x: int(x) > 2006),'ETABLI2']=df.loc[df['RENTREE'].apply(lambda x: int(x) > 2006),'ETABLI']

if rentree_sco in ["2014","2013","2012","2011","2010","2009","2008","2007"]:
    df=df[['RENTREE','PAYS_ID','REG_ID','ACA_ID','DEP_ID','UUCR_ID','COM_CODE2','COM_CODE','ETABLI','RGP3','FORMAT','SECT','INSPE','IUT','IUT2','ING','TOTAL','LMDDONT','DISCIPLI','CURSUS_LMD','UNIV','STS_ASS','DUT','SEXE','UUCR_NOM','DEP_NUM_NOM','ACA_NOM','REG_NOM','EFFTOT']]
elif int(rentree_sco) > 2016:
    df=df[['RENTREE','PAYS_ID','REG_ID','ACA_ID','DEP_ID','UUCR_ID','COM_CODE2','COM_CODE','ETABLI','RGP3','FORMAT','SECT','INSPE','IUT','IUT2','ING','TOTAL','LMDDONT','DISCIPLI','CURSUS_LMD','UNIV','STS_ASS','DUT','SEXE','UUCR_NOM','DEP_NUM_NOM','ACA_NOM','REG_NOM','EFFTOT','EFFSDC', 'EFF_STS_APP',]]
elif rentree_sco in ["2006","2005","2004","2003","2002","2001"]:
    df=df[['RENTREE','PAYS_ID','REG_ID','ACA_ID','DEP_ID','UUCR_ID','COM_CODE2','COM_CODE','ETABLI','RGP3','FORMAT','SECT','INSPE','IUT','IUT2','ING','TOTAL','UNIV','STS_ASS','DUT','SEXE','UUCR_NOM','DEP_NUM_NOM','ACA_NOM','REG_NOM','EFFTOT']]

if rentree_sco in ["2014","2013","2012","2011","2010","2009","2008","2007"]:
    df=df.groupby(['RENTREE','PAYS_ID','REG_ID','ACA_ID','DEP_ID','UUCR_ID','COM_CODE2','COM_CODE','ETABLI','RGP3','FORMAT','SECT','INSPE','IUT','IUT2','ING','TOTAL','LMDDONT','DISCIPLI','CURSUS_LMD','UNIV','STS_ASS','DUT','SEXE','UUCR_NOM','DEP_NUM_NOM','ACA_NOM','REG_NOM'], as_index=False, dropna=False).agg({'EFFTOT': 'sum'}) 
elif int(rentree_sco) > 2016:
    df=df.groupby(['RENTREE','PAYS_ID','REG_ID','ACA_ID','DEP_ID','UUCR_ID','COM_CODE2','COM_CODE','ETABLI','RGP3','FORMAT','SECT','INSPE','IUT','IUT2','ING','TOTAL','LMDDONT','DISCIPLI','CURSUS_LMD','UNIV','STS_ASS','DUT','SEXE','UUCR_NOM','DEP_NUM_NOM','ACA_NOM','REG_NOM'], as_index=False, dropna=False).agg({'EFFTOT': 'sum','EFFSDC': 'sum', 'EFF_STS_APP':'sum'}) 
elif rentree_sco in ["2006","2005","2004","2003","2002","2001"]:
    df=df.groupby(['RENTREE','PAYS_ID','REG_ID','ACA_ID','DEP_ID','UUCR_ID','COM_CODE2','COM_CODE','ETABLI','RGP3','FORMAT','SECT','INSPE','IUT','IUT2','ING','TOTAL','UNIV','STS_ASS','DUT','SEXE','UUCR_NOM','DEP_NUM_NOM','ACA_NOM','REG_NOM'], as_index=False, dropna=False).agg({'EFFTOT': 'sum'}) 
df.loc[df['RGP3']=='UNIV_PRIV','RGP3']='EPEU'
df=df.rename(columns={'DEP_NUM_NOM':'DEP_NOM'})
# nouvelle variable effectif_atlas
if df.RENTREE[0] > 2014:
    df['effectif_atlas']=df.loc[:,'EFFSDC']
if df.RENTREE[0] <= 2014:    
    df['effectif_atlas']=df.loc[:,'EFFTOT']

C:\Users\haallat\AppData\Local\Temp\ipykernel_6380\2584558149.py:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'UNIV' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df['RGP3']=='UNIV','UNIV']='UNIV'
C:\Users\haallat\AppData\Local\Temp\ipykernel_6380\2584558149.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[~df['RGP3'].isin(["ENS","GE","INP","IUFM","UNIV","UT"]),'CURSUS_LMD']=""

In [18]:
df.loc[df.RENTREE.apply(lambda x: int(x) > 2014)]

Empty DataFrame
Columns: [RENTREE, PAYS_ID, REG_ID, ACA_ID, DEP_ID, UUCR_ID, COM_CODE2, COM_CODE, ETABLI, RGP3, FORMAT, SECT, INSPE, IUT, IUT2, ING, TOTAL, UNIV, STS_ASS, DUT, SEXE, UUCR_NOM, DEP_NOM, ACA_NOM, REG_NOM, EFFTOT, effectif_atlas]
Index: []

[0 rows x 27 columns]

In [19]:
dict_rentree={}
dict_annee={}
for year in range(2001,int(datetime.now().year)):
    dict_annee[str(year)]=str(year + 1)
    if year < 2009:
        dict_rentree[str(year)]=f"{year}-0{int(str(year)[2:])+1}"
    else:
        dict_rentree[str(year)]=f"{year}-{int(str(year)[2:])+1}"
rentree=pd.DataFrame(dict_rentree.items(), columns=['RENTREE', 'annee_universitaire'])
annee=pd.DataFrame(dict_annee.items(), columns=['RENTREE', 'annee'])

In [20]:
NIVEAU=pd.DataFrame({"ACADEMIE":"Académie","COMMUNE":"Commune","DEPARTEMENT":"Département","PAYS":"Pays","REGION":"Région","UNITE_URBAINE":"Unité urbaine"}.items(), columns=['NIVEAU', 'niveau_geographique'])
rgp=pd.DataFrame({"CPGE":"Classes préparatoires aux grandes écoles (CPGE)","EC_ART":"Écoles supérieures art et culture","EC_autres":"Autres écoles de spécialités diverses","EC_COM":"Écoles de commerce, gestion et comptabilité","EC_JUR":"Écoles juridiques et administratives","EC_PARAM":"Écoles paramédicales et sociales","ENS":"Écoles normales supérieures (ENS)","GE":"Grands établissements MESRE","ING_autres":"Autres formations d'ingénieurs","INP":"Instituts nationaux polytechniques (INP)","IUFM":"Instituts universitaires de formation des maîtres","STS":"Sections de techniciens supérieurs (STS) et assimilés","TOTAL":"Total des formations d'enseignement supérieur","UNIV":"Universités","EPEU":"Établissements d'enseignement universitaire privés","UT":"Universités de technologie (UT)"}.items(), columns=['RGP3', 'rgp_formations_ou_etablissements'])
sect=pd.DataFrame({"PU":"Établissements publics","PR":"Établissements privés"}.items(), columns=['SECT', 'secteur_de_l_etablissement'])
sexe=pd.DataFrame({"1":"Masculin","2":"Feminin"}.items(), columns=['SEXE', 'sexe_de_l_etudiant'])
niveau=['PAYS','REGION','ACADEMIE','DEPARTEMENT','UNITE_URBAINE','COMMUNE']
tab=['PAYS','REGIONS','ACADEMIES','DEPARTEMENTS','UNITE_URBAINES','COMMUNES']
varid=[['PAYS_ID'],['REG_ID'],['ACA_ID'],['DEP_ID'],['UUCR_ID'],['COM_CODE']]
varlib=['PAYS_NOM','REG_NOM','ACA_NOM','DEP_NOM','UUCR_NOM','COM_NOM']
geolist=['','REG','REG ACA','REG ACA DEP','REG UUCR','REG ACA DEP UUCR']
geolist2=['','reg_id','reg_id aca_id','reg_id aca_id dep_id','reg_id uucr_id','reg_id aca_id dep_id uucr_id']
geolist3=['','reg_nom','reg_nom aca_nom','reg_nom aca_nom dep_nom','reg_nom uucr_nom','reg_nom aca_nom dep_nom uucr_nom']
df['REG']=df.loc[:,'REG_ID']
df['ACA']=df.loc[:,'ACA_ID']
df['DEP']=df.loc[:,'DEP_ID']
df['UUCR']=df.loc[:,'UUCR_ID']
dict_a={'RENTREE':'rentree','EFFTOT':'effectif','EFFSDC':'effectifhdccpge','SEXE':'sexe','SECT':'secteur','RGP3':'regroupement','PAYS_ID':'geo_id','REG_ID':'geo_id','ACA_ID':'geo_id','DEP_ID':'geo_id','UUCR_ID':'geo_id','COM_CODE':'geo_id'}
dict_b={'PAYS_NOM':'geo_nom','REG_NOM':'geo_nom','ACA_NOM':'geo_nom','DEP_NOM':'geo_nom','UUCR_NOM':'geo_nom','COM_NOM':'geo_nom'}
dict_c={'EFFTOT':'effectif_dut'}
dict_d={'EFFTOT':'effectif_ing'}
dict_e={'EFFTOT':'effectif_form_ens'}
dict_g={'EFF_STS_APP':'effectif_apprentis_en_sts'}
dict_f={'ACA':'aca_id','DEP':'dep_id','UUCR':'uucr_id','REG':'reg_id'}
df['RENTREE']=df['RENTREE'].astype('str')
df['SEXE']=df['SEXE'].astype('str')
communes['pays']=communes.loc[:,'REG_ID'].apply(lambda x: 'Étranger' if x=='R99' else 'France')

In [21]:
for i in range(6):
    if 'EFFSDC' not in df.columns:
        df['EFFSDC']=0
    if 'EFF_STS_APP' not in df.columns:
        df['EFF_STS_APP']=0
    print(i)
    if i==0:
        t1=df.groupby(['RENTREE','RGP3','SECT','SEXE']+varid[i], as_index=False, dropna=False).agg({'EFFTOT': 'sum','effectif_atlas': 'sum','EFFSDC': 'sum'}) 
        t2=df.loc[df['ING']=='ING'].groupby(['RENTREE','RGP3','SECT','SEXE']+varid[i], as_index=False, dropna=False).agg({'EFFTOT': 'sum','effectif_atlas': 'sum','EFFSDC': 'sum'}) 
        t3=df.loc[df['IUT']=='IUT'].groupby(['RENTREE','RGP3','SECT','SEXE']+varid[i], as_index=False, dropna=False).agg({'EFFTOT': 'sum','effectif_atlas': 'sum','EFFSDC': 'sum'}) 
        t4=df.loc[df['INSPE']=='ESPE'].groupby(['RENTREE','RGP3','SECT','SEXE']+varid[i], as_index=False, dropna=False).agg({'EFFTOT': 'sum','effectif_atlas': 'sum','EFFSDC': 'sum'}) 
        t5=df.loc[df['EFF_STS_APP']!=0].groupby(['RENTREE','RGP3','SECT','SEXE']+varid[i], as_index=False, dropna=False).agg({'EFF_STS_APP':'sum'}) 
        
        t11=t1.groupby(['RENTREE','SECT','SEXE']+varid[i], as_index=False, dropna=False).agg({'EFFTOT': 'sum','EFFSDC': 'sum'}) 
        t22=t2.groupby(['RENTREE','RGP3','SECT','SEXE']+varid[i], as_index=False, dropna=False).agg({'EFFTOT': 'sum','EFFSDC': 'sum'}) 
        t33=t3.groupby(['RENTREE','SECT','SEXE']+varid[i], as_index=False, dropna=False).agg({'EFFTOT': 'sum','EFFSDC': 'sum'}) 
        t44=t4.groupby(['RENTREE','SECT','SEXE']+varid[i], as_index=False, dropna=False).agg({'EFFTOT': 'sum','EFFSDC': 'sum'}) 
        t55=t5.groupby(['RENTREE','SECT','SEXE']+varid[i], as_index=False, dropna=False).agg({'EFF_STS_APP':'sum'}) 
    else:
        t1=df.groupby(['RENTREE','RGP3','SECT','SEXE']+varid[i]+list(geolist[i].split(' ')), as_index=False, dropna=False).agg({'EFFTOT': 'sum','effectif_atlas': 'sum','EFFSDC': 'sum'}) 
        t2=df.loc[df['ING']=='ING'].groupby(['RENTREE','RGP3','SECT','SEXE']+varid[i]+geolist[i].split(' '), as_index=False, dropna=False).agg({'EFFTOT': 'sum','effectif_atlas': 'sum','EFFSDC': 'sum'}) 
        t3=df.loc[df['IUT']=='IUT'].groupby(['RENTREE','RGP3','SECT','SEXE']+varid[i]+geolist[i].split(' '), as_index=False, dropna=False).agg({'EFFTOT': 'sum','effectif_atlas': 'sum','EFFSDC': 'sum'}) 
        t4=df.loc[df['INSPE']=='ESPE'].groupby(['RENTREE','RGP3','SECT','SEXE']+varid[i]+geolist[i].split(' '), as_index=False, dropna=False).agg({'EFFTOT': 'sum','effectif_atlas': 'sum','EFFSDC': 'sum'}) 
        t5=df.loc[df['EFF_STS_APP']!=0].groupby(['RENTREE','RGP3','SECT','SEXE']+varid[i]+geolist[i].split(' '), as_index=False, dropna=False).agg({'EFF_STS_APP':'sum'}) 


        t11=t1.groupby(['RENTREE','SECT','SEXE']+varid[i]+geolist[i].split(' '), as_index=False, dropna=False).agg({'EFFTOT': 'sum','effectif_atlas': 'sum','EFFSDC': 'sum'}) 
        t22=t2.groupby(['RENTREE','RGP3','SECT','SEXE']+varid[i]+geolist[i].split(' '), as_index=False, dropna=False).agg({'EFFTOT': 'sum','effectif_atlas': 'sum','EFFSDC': 'sum'}) 
        t33=t3.groupby(['RENTREE','SECT','SEXE']+varid[i]+geolist[i].split(' '), as_index=False, dropna=False).agg({'EFFTOT': 'sum','effectif_atlas': 'sum','EFFSDC': 'sum'}) 
        t44=t4.groupby(['RENTREE','SECT','SEXE']+varid[i]+geolist[i].split(' '), as_index=False, dropna=False).agg({'EFFTOT': 'sum','effectif_atlas': 'sum','EFFSDC': 'sum'}) 
        t55=t5.groupby(['RENTREE','SECT','SEXE']+varid[i]+geolist[i].split(' '), as_index=False, dropna=False).agg({'EFF_STS_APP':'sum'}) 
    
    t111=pd.concat([t1,t11])
    t111.loc[pd.isna(t111['RGP3']),'RGP3']='TOTAL'
    t111['NIVEAU']=[niveau[i] for x in range(0,len(t111))]
    t111=pd.merge(t111,rentree,on='RENTREE',how='left')
    t111=pd.merge(t111,annee,on='RENTREE',how='left')
    t111=pd.merge(t111,NIVEAU,on='NIVEAU',how='left')
    t111=pd.merge(t111,rgp,on='RGP3',how='left')
    t111=pd.merge(t111,sect,on='SECT',how='left')
    t111=pd.merge(t111,sexe,on='SEXE',how='left')
    t111['niveau_geo']=t111.loc[:,'NIVEAU']

    t222=pd.concat([t2,t22])
    t222.loc[pd.isna(t222['RGP3']),'RGP3']='TOTAL'

    t333=pd.concat([t3,t33])
    t333.loc[pd.isna(t333['RGP3']),'RGP3']='TOTAL'

    t444=pd.concat([t4,t44])
    t444.loc[pd.isna(t444['RGP3']),'RGP3']='TOTAL'

    t555=pd.concat([t5,t55])
    t555.loc[pd.isna(t555['RGP3']),'RGP3']='TOTAL'

    if i==0:
        A=['RENTREE','annee_universitaire','annee','niveau_geo','niveau_geographique','RGP3','rgp_formations_ou_etablissements','SECT','secteur_de_l_etablissement','SEXE','sexe_de_l_etudiant','EFFTOT','EFFSDC','effectif_atlas']+varid[i]
        df1=t111[A]
        df1['pays']=df1.loc[:,'PAYS_ID'].apply(lambda x: 'Étranger' if x=='PAYS_999' else 'France')
        df1=df1.rename(columns=dict_a)
        df1=df1.rename(columns=dict_b)
        print(df1.columns)
    else:
        A=['RENTREE','annee_universitaire','annee','niveau_geo','niveau_geographique','RGP3','rgp_formations_ou_etablissements','SECT','secteur_de_l_etablissement','SEXE','sexe_de_l_etudiant','EFFTOT','EFFSDC','effectif_atlas']+varid[i]+geolist[i].split(' ')
        T=t111[A].rename(columns=dict_a)
        C=communes[[varlib[i],varid[i][0],'pays']].rename(columns=dict_b).drop_duplicates()
        df1=pd.merge(T,C,how= 'left', left_on='geo_id', right_on=varid[i][0])
        del df1[varid[i][0]]
        print(df1.columns)
    
    df2=pd.merge(df1,t333[['EFFTOT','RGP3','SECT','SEXE',varid[i][0]]].rename(columns=dict_c).drop_duplicates(),how= 'left', left_on=['geo_id','regroupement','secteur','sexe'], right_on = [varid[i][0],'RGP3','SECT','SEXE'])
    df2=df2.drop([varid[i][0],'RGP3','SECT','SEXE'], axis=1)
    df3=pd.merge(df2,t222[['EFFTOT','RGP3','SECT','SEXE',varid[i][0]]].rename(columns=dict_d).drop_duplicates(),how= 'left', left_on=['geo_id','regroupement','secteur','sexe'], right_on = [varid[i][0],'RGP3','SECT','SEXE'])
    df3=df3.drop([varid[i][0],'RGP3','SECT','SEXE'], axis=1)
    df4=pd.merge(df3,t444[['EFFTOT','RGP3','SECT','SEXE',varid[i][0]]].rename(columns=dict_e).drop_duplicates(),how= 'left', left_on=['geo_id','regroupement','secteur','sexe'], right_on = [varid[i][0],'RGP3','SECT','SEXE'])
    df4=df4.drop([varid[i][0],'RGP3','SECT','SEXE'], axis=1)
    df5=pd.merge(df4,t555[['EFF_STS_APP','RGP3','SECT','SEXE',varid[i][0]]].rename(columns=dict_g).drop_duplicates(),how= 'left', left_on=['geo_id','regroupement','secteur','sexe'], right_on = [varid[i][0],'RGP3','SECT','SEXE'])
    df5=df5.drop([varid[i][0],'RGP3','SECT','SEXE'], axis=1)

    df5['geo_id']=df5.loc[:,'geo_id'].apply(lambda x: 'PAYS_AUTRE' if x=='PAYS_999' else x)

    df5['effectif_dut']=df5.loc[:,'effectif_dut'].apply(lambda x: 0 if pd.isna(x) else x)
    df5['effectif_ing']=df5.loc[:,'effectif_ing'].apply(lambda x: 0 if pd.isna(x) else x)
    df5['effectif_form_ens']=df5.loc[:,'effectif_form_ens'].apply(lambda x: 0 if pd.isna(x) else x)
    df5['effectif_apprentis_en_sts']=df5.loc[:,'effectif_apprentis_en_sts'].apply(lambda x: 0 if pd.isna(x) else x)


    if i==0:
        df6=df5.drop_duplicates(subset=['rentree', 'annee_universitaire', 'annee', 'niveau_geo','niveau_geographique', 'regroupement',
        'rgp_formations_ou_etablissements', 'secteur',
        'secteur_de_l_etablissement', 'sexe', 'sexe_de_l_etudiant', 'effectif',
        'effectifhdccpge', 'effectif_atlas', 'geo_id','pays'])

        df7=df6.groupby(['rentree', 'annee_universitaire', 'annee', 'niveau_geo','niveau_geographique', 'regroupement',
            'rgp_formations_ou_etablissements', 'secteur',
            'secteur_de_l_etablissement', 'sexe', 'sexe_de_l_etudiant', 'geo_id','pays'], as_index=False, dropna=False).agg({'effectif': 'sum','effectif_atlas': 'sum','effectifhdccpge': 'sum','effectif_dut': 'sum','effectif_ing': 'sum','effectif_form_ens': 'sum','effectif_apprentis_en_sts':'sum'}) 
    
    else:
        l1=['rentree', 'annee_universitaire', 'annee', 'niveau_geo','niveau_geographique', 'regroupement',
        'rgp_formations_ou_etablissements', 'secteur',
        'secteur_de_l_etablissement', 'sexe', 'sexe_de_l_etudiant', 'effectif',
        'effectifhdccpge','effectif_atlas','effectif_apprentis_en_sts','geo_id', 'geo_nom']+geolist2[i].split(' ')+['pays']
        df6=df5.rename(columns=dict_f).drop_duplicates(subset=l1)

        l2=['rentree', 'annee_universitaire', 'annee', 'niveau_geo','niveau_geographique', 'regroupement',
            'rgp_formations_ou_etablissements', 'secteur',
            'secteur_de_l_etablissement', 'sexe', 'sexe_de_l_etudiant', 'geo_id', 'geo_nom']+geolist2[i].split(' ')+['pays']
        df7=df6.groupby(l2, as_index=False, dropna=False).agg({'effectif': 'sum', 'effectif_atlas': 'sum', 'effectifhdccpge': 'sum','effectif_dut': 'sum','effectif_ing': 'sum','effectif_form_ens': 'sum','effectif_apprentis_en_sts':'sum'}) 

    df7['a_des_effectifs_dut']=df7.loc[:,'effectif_dut'].apply(lambda x: 'oui' if x>0 else 'non')
    df7['a_des_effectifs_ing']=df7.loc[:,'effectif_ing'].apply(lambda x: 'oui' if x>0 else 'non')
    df7['a_des_effectifs_form_ens']=df7.loc[:,'effectif_form_ens'].apply(lambda x: 'oui' if x>0 else 'non')
    df7['a_des_effectifs_apprentis_sts']=df7.loc[:,'effectif_apprentis_en_sts'].apply(lambda x: 'oui' if x>0 else 'non')

    df8=df7[df7.effectif!=0]
    if i==4:
        df8['uu']=df8['geo_id'].apply(lambda x: True if str(x)[:2]=='UU' else False)
        df8=df8[df8['uu']==True]
        del df8['uu']
    niveau[i]=df8

0
Index(['rentree', 'annee_universitaire', 'annee', 'niveau_geo',
       'niveau_geographique', 'regroupement',
       'rgp_formations_ou_etablissements', 'secteur',
       'secteur_de_l_etablissement', 'sexe', 'sexe_de_l_etudiant', 'effectif',
       'effectifhdccpge', 'effectif_atlas', 'geo_id', 'pays'],
      dtype='object')
1
Index(['rentree', 'annee_universitaire', 'annee', 'niveau_geo',
       'niveau_geographique', 'regroupement',
       'rgp_formations_ou_etablissements', 'secteur',
       'secteur_de_l_etablissement', 'sexe', 'sexe_de_l_etudiant', 'effectif',
       'effectifhdccpge', 'effectif_atlas', 'geo_id', 'REG', 'geo_nom',
       'pays'],
      dtype='object')
2
Index(['rentree', 'annee_universitaire', 'annee', 'niveau_geo',
       'niveau_geographique', 'regroupement',
       'rgp_formations_ou_etablissements', 'secteur',
       'secteur_de_l_etablissement', 'sexe', 'sexe_de_l_etudiant', 'effectif',
       'effectifhdccpge', 'effectif_atlas', 'geo_id', 'REG', 'ACA', 'geo_nom',
       'pays'],
      dtype='object')
3
Index(['rentree', 'annee_universitaire', 'annee', 'niveau_geo',
       'niveau_geographique', 'regroupement',
       'rgp_formations_ou_etablissements', 'secteur',
       'secteur_de_l_etablissement', 'sexe', 'sexe_de_l_etudiant', 'effectif',
       'effectifhdccpge', 'effectif_atlas', 'geo_id', 'REG', 'ACA', 'DEP',
       'geo_nom', 'pays'],
      dtype='object')
4
Index(['rentree', 'annee_universitaire', 'annee', 'niveau_geo',
       'niveau_geographique', 'regroupement',
       'rgp_formations_ou_etablissements', 'secteur',
       'secteur_de_l_etablissement', 'sexe', 'sexe_de_l_etudiant', 'effectif',
       'effectifhdccpge', 'effectif_atlas', 'geo_id', 'REG', 'UUCR', 'geo_nom',
       'pays'],
      dtype='object')
5
Index(['rentree', 'annee_universitaire', 'annee', 'niveau_geo',
       'niveau_geographique', 'regroupement',
       'rgp_formations_ou_etablissements', 'secteur',
       'secteur_de_l_etablissement', 'sexe', 'sexe_de_l_etudiant', 'effectif',
       'effectifhdccpge', 'effectif_atlas', 'geo_id', 'REG', 'ACA', 'DEP',
       'UUCR', 'geo_nom', 'pays'],
      dtype='object')

In [22]:
#concat tous les niveaux de geo_id

In [23]:
df_all=pd.concat([niveau[0],niveau[1],niveau[2],niveau[3],niveau[4],niveau[5]])
df_all.index=[x for x in range(len(df_all))]

In [24]:
df_all.columns

Index(['rentree', 'annee_universitaire', 'annee', 'niveau_geo',
       'niveau_geographique', 'regroupement',
       'rgp_formations_ou_etablissements', 'secteur',
       'secteur_de_l_etablissement', 'sexe', 'sexe_de_l_etudiant', 'geo_id',
       'pays', 'effectif', 'effectif_atlas', 'effectifhdccpge', 'effectif_dut',
       'effectif_ing', 'effectif_form_ens', 'effectif_apprentis_en_sts',
       'a_des_effectifs_dut', 'a_des_effectifs_ing',
       'a_des_effectifs_form_ens', 'a_des_effectifs_apprentis_sts', 'geo_nom',
       'reg_id', 'aca_id', 'dep_id', 'uucr_id'],
      dtype='object')

In [25]:
df_all=df_all[['rentree', 'annee_universitaire', 'annee', 'regroupement','niveau_geo','niveau_geographique',
       'rgp_formations_ou_etablissements', 'secteur',
       'secteur_de_l_etablissement', 'sexe', 'sexe_de_l_etudiant', 'geo_id',
       'effectif', 'effectifhdccpge', 'effectif_atlas', 'effectif_dut', 'effectif_ing',
       'effectif_form_ens', 'effectif_apprentis_en_sts', 'a_des_effectifs_dut',
       'a_des_effectifs_ing', 'a_des_effectifs_form_ens',
       'a_des_effectifs_apprentis_sts', 'geo_nom', 'pays', 'reg_id', 'aca_id',
       'dep_id', 'uucr_id']]

In [26]:
df_all.to_json(f"./OUTPUT_OPENDATA/atlas{rentree_sco}.json", orient='records')

In [27]:
df_all=pd.read_json(f"./OUTPUT_OPENDATA/atlas{rentree_sco}.json")

In [28]:
df_all[df_all.geo_id=='nan']

Empty DataFrame
Columns: [rentree, annee_universitaire, annee, regroupement, niveau_geo, niveau_geographique, rgp_formations_ou_etablissements, secteur, secteur_de_l_etablissement, sexe, sexe_de_l_etudiant, geo_id, effectif, effectifhdccpge, effectif_atlas, effectif_dut, effectif_ing, effectif_form_ens, effectif_apprentis_en_sts, a_des_effectifs_dut, a_des_effectifs_ing, a_des_effectifs_form_ens, a_des_effectifs_apprentis_sts, geo_nom, pays, reg_id, aca_id, dep_id, uucr_id]
Index: []

[0 rows x 29 columns]

Une fois qu'on a fait tourner ce qu'il y a au dessus pour chaque année (à moins qu'il n'y ait pas de changement dans le code, on peut garder les output des années précédentes j'imagine), on concatene toutes les années ensemble

In [29]:
rentree_sco='2025'

In [30]:
df1=pd.read_json(f"./OUTPUT_OPENDATA/atlas2001.json")
for i in range(2002,int(rentree_sco)+1,1):
    df2=pd.read_json(f"./OUTPUT_OPENDATA/atlas{i}.json")
    df1=pd.concat([df1,df2])

In [31]:
df=df1.sort_values(by=["rentree"], ascending=False)

In [32]:
df_tot=df.reset_index()
del df_tot['index']

In [33]:
df_tot

,rentree,annee_universitaire,annee,regroupement,niveau_geo,niveau_geographique,rgp_formations_ou_etablissements,secteur,secteur_de_l_etablissement,sexe,...,a_des_effectifs_dut,a_des_effectifs_ing,a_des_effectifs_form_ens,a_des_effectifs_apprentis_sts,geo_nom,pays,reg_id,aca_id,dep_id,uucr_id
0,2025,2025-26,2026,UNIV,COMMUNE,Commune,Universités,PU,Établissements publics,2,...,oui,oui,oui,non,Perpignan,France,R76,A11,D066,UU66701
1,2025,2025-26,2026,UNIV,COMMUNE,Commune,Universités,PU,Établissements publics,2,...,oui,oui,oui,non,Limoges,France,R75,A22,D087,UU87601
2,2025,2025-26,2026,UNIV,COMMUNE,Commune,Universités,PU,Établissements publics,2,...,oui,non,non,non,Cachan,France,R11,A24,D094,UU00851
3,2025,2025-26,2026,UT,COMMUNE,Commune,Universités de technologie (UT),PU,Établissements publics,2,...,non,oui,non,non,Sevenans,France,R27,A03,D090,CR90094
4,2025,2025-26,2026,UT,COMMUNE,Commune,Universités de technologie (UT),PU,Établissements publics,2,...,non,oui,non,non,Belfort,France,R27,A03,D090,UU00558
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491012,2001,2001-02,2002,INP,PAYS,Pays,Instituts nationaux polytechniques (INP),PU,Établissements publics,2,...,non,oui,non,non,None,France,None,None,None,None
491013,2001,2001-02,2002,IUFM,PAYS,Pays,Instituts universitaires de formation des maîtres,PU,Établissements publics,1,...,non,non,non,non,None,France,None,None,None,None
491014,2001,2001-02,2002,IUFM,PAYS,Pays,Instituts universitaires de formation des maîtres,PU,Établissements publics,2,...,non,non,non,non,None,France,None,None,None,None
491015,2001,2001-02,2002,STS,PAYS,Pays,Sections de techniciens supérieurs (STS) et as...,PR,Établissements privés,1,...,non,non,non,non,None,France,None,None,None,None
491016,2001,2001-02,2002,EC_ART,REGION,Région,Écoles supérieures art et culture,PU,Établissements publics,2,...,non,non,non,non,Grand Est,France,R44,None,None,None

In [34]:
df_tot=df_tot[['rentree', 'annee_universitaire', 'annee', 'regroupement', 'niveau_geo',
       'niveau_geographique', 'rgp_formations_ou_etablissements', 'secteur',
       'secteur_de_l_etablissement', 'sexe', 'sexe_de_l_etudiant', 'geo_id',
       'effectif', 'effectifhdccpge', 'effectif_atlas', 'effectif_dut', 'effectif_ing',
       'effectif_form_ens', 'effectif_apprentis_en_sts', 'a_des_effectifs_dut',
       'a_des_effectifs_ing', 'a_des_effectifs_form_ens',
       'a_des_effectifs_apprentis_sts', 'geo_nom', 'pays', 'reg_id', 'aca_id',
       'dep_id', 'uucr_id']]

In [35]:
df_tot.loc[:,'rgp_formations_ou_etablissements']=df_tot.loc[:,'rgp_formations_ou_etablissements'].apply(lambda x: str(x).replace("Grands établissements MENESR","Grands établissements MESRE"))

In [36]:
df_tot.loc[:,'rgp_formations_ou_etablissements'].value_counts()

rgp_formations_ou_etablissements
Total des formations d'enseignement supérieur            140641
Sections de techniciens supérieurs (STS) et assimilés    127938
Écoles paramédicales et sociales                          47139
Autres écoles de spécialités diverses                     35503
Classes préparatoires aux grandes écoles (CPGE)           31172
Universités                                               28896
Écoles supérieures art et culture                         21830
Écoles de commerce, gestion et comptabilité               16500
Autres formations d'ingénieurs                            16227
Écoles juridiques et administratives                       7642
Grands établissements MESRE                                5705
Instituts universitaires de formation des maîtres          5386
Établissements d'enseignement universitaire privés         4150
Universités de technologie (UT)                             972
Écoles normales supérieures (ENS)                           846
Instituts nationaux polytechniques (INP)                    470
Name: count, dtype: int64

In [37]:
df_com=df_tot

In [38]:
del df_tot['pays']

In [39]:
df_tot=remplacer_nan_par_vide(df_tot)

In [40]:
df_tot.to_json("./OUTPUT_OPENDATA/OD_atlas_all.json", orient='records')

In [41]:
df_tot.to_csv("./OUTPUT_OPENDATA/OD_atlas_all.csv", sep=";", encoding="UTF-8", index=False)

juste les communes

In [43]:
communes['pays']=communes.loc[:,'REG_ID'].apply(lambda x: 'Étranger' if x=='R99' else 'France')

In [44]:
df_com=df_com[(df_com.niveau_geo=='COMMUNE')&(df_com.regroupement!='TOTAL')].rename(columns={"geo_id":"com_id", "geo_nom":"com_nom"})

In [45]:
df_com=pd.merge(df_com,communes[['COM_CODE','UUCR_NOM','DEP_NOM','ACA_NOM','REG_NOM']], how='left', left_on='com_id', right_on='COM_CODE')

In [46]:
del df_com['niveau_geo']
del df_com['niveau_geographique']

In [47]:
'pays' in list(df_com.columns)

False

In [48]:
df_com=remplacer_nan_par_vide(df_com)

In [49]:
df_com.to_json(f"./OUTPUT_OPENDATA/OD_atlas_all_com.json", orient='records')
df_com.to_csv("./OUTPUT_OPENDATA/OD_atlas_all_com.csv", sep=";", encoding="UTF-8", index=False)

Checks par rapport à l'année dernière

In [50]:
df_ancien=pd.read_csv("./OUTPUT_OPENDATA/OD_atlas_all_com_ancien.csv", sep=";")

In [51]:
df_nouveau=pd.read_csv("./OUTPUT_OPENDATA/OD_atlas_all_com.csv", sep=";")

In [52]:
df_ancien[df_ancien.annee_universitaire=='2022-23'].groupby('regroupement')['effectif_atlas'].sum()

regroupement
CPGE            81674
EC_ART         110520
EC_COM         244979
EC_JUR           9254
EC_PARAM       153718
EC_autres       76270
ENS              2297
EPEU            45823
GE             107717
ING_autres     100691
INP              4148
STS            409684
UNIV          1590560
UT              10018
Name: effectif_atlas, dtype: int64

Etape 1: Comparer les df

In [53]:
cols = list(df_nouveau.columns)
df_nouveau = df_nouveau.sort_values(cols).reset_index(drop=True)
df_anciens = df_ancien.sort_values(cols).reset_index(drop=True)

In [54]:
df_nouveau.equals(df_anciens)  # True = identiques, False = il y a des différences

False

Etape 2: voir les lignes qui diffèrent

In [55]:
diff = df_nouveau[['rentree','regroupement','com_id','sexe_de_l_etudiant','effectif_atlas']].merge(df_anciens[['rentree','regroupement','com_id','sexe_de_l_etudiant','effectif_atlas']], how='outer', indicator=True).drop_duplicates(subset=['rentree','regroupement','com_id','sexe_de_l_etudiant','effectif_atlas'])
diff = diff[diff['_merge'] != 'both'][['rentree','regroupement','com_id','sexe_de_l_etudiant','effectif_atlas','_merge']]
diff['_merge'] = diff['_merge'].map({'left_only': 'df_coms', 'right_only': 'df_anciens'})
print(diff)

        rentree regroupement com_id sexe_de_l_etudiant  effectif_atlas  \
2530       2001           GE  26362            Feminin              31
2531       2001           GE  26362           Masculin             213
2534       2001           GE  38185            Feminin             357
2535       2001           GE  38185           Masculin            1333
2536       2001           GE  38421            Feminin             628
...         ...          ...    ...                ...             ...
165438     2025           UT  65440           Masculin            2092
165439     2025           UT  90010            Feminin             176
165440     2025           UT  90010           Masculin             740
165441     2025           UT  90094            Feminin             221
165442     2025           UT  90094           Masculin            1043

         _merge
2530    df_coms
2531    df_coms
2534    df_coms
2535    df_coms
2536    df_coms
...         ...
165438  df_coms
165439  df_coms
165440  df_coms
165441  df_coms
165442  df_coms

[7908 rows x 6 columns]

In [56]:
pd.DataFrame(diff).to_csv("difference.csv", sep=";", encoding="UTF-8")

Etape 3 : voir les colonnes problematiques par ligne

In [ ]:
#df_coms.compare(df_anciens)